name: deploy 
run-name: Terraform apply on the push to main branch
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
      - run: make deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          BUCKET_KEY: ${{ vars.BUCKET_KEY }}
          BUCKET_NAME: ${{ vars.BUCKET_NAME }}
          TF_VAR_DOCKER_CONFIG_JSON: ${{ vars.TF_VAR_DOCKER_CONFIG_JSON }}
          TF_VAR_XALT_TECHNICAL_ASSISTANT_ID_RSA: ${{ vars.TF_VAR_XALT_TECHNICAL_ASSISTANT_ID_RSA }}
          TF_VAR_CONTAINER_DEMO_ID_RSA: ${{ vars.TF_VAR_CONTAINER_DEMO_ID_RSA }}
